#!/usr/bin/env bash
#Script that transfers a file from our client to a server

# Check if all parameters are provided
if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

file_path=/alx-system_engineering-devops/0x0C-webserver/somepage.html # Path to the file on the local machine
server_ip=100.25.191.169
username=ubuntu
ssh_key=/home/aliasaad/.ssh/id_rsa


# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~/"

exit 0
